package backup

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"context"
	"database/sql"
	"encoding/hex"
	"errors"
	"io"
	"os"
	"path/filepath"
	"strings"
	"sync/atomic"
	"testing"
	"time"

	"github.com/botnick/telegram-media-downloader/core-service/internal/store"
)

func fixtureManager(t *testing.T, factory Factory) (*Manager, *store.DB, string) {
	t.Helper()
	dir := t.TempDir()
	db, err := store.Open(context.Background(), dir)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { db.Reader.Close(); db.Writer.Close() })
	if err = os.MkdirAll(filepath.Join(dir, "downloads"), 0700); err != nil {
		t.Fatal(err)
	}
	opts := Options{Writer: db.Writer, Reader: db.Reader, DataDir: dir, Secret: func(context.Context) ([]byte, error) { return bytes.Repeat([]byte{0x11}, 32), nil }, Factory: factory}
	m, err := NewManager(context.Background(), opts)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(m.Close)
	return m, db, dir
}
func addLocal(t *testing.T, m *Manager, root, mode string) int64 {
	t.Helper()
	input := map[string]any{"name": "fixture", "provider": "local", "config": map[string]any{"rootPath": root}, "mode": mode}
	if mode == "snapshot" {
		input["cron"] = "* * * * *"
	}
	d, err := m.Create(context.Background(), input)
	if err != nil {
		t.Fatal(err)
	}
	return d["id"].(int64)
}
func addSource(t *testing.T, db *store.DB, dir, name, content string, msg int) int64 {
	t.Helper()
	file := filepath.Join(dir, "downloads", name)
	if err := os.MkdirAll(filepath.Dir(file), 0700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(file, []byte(content), 0600); err != nil {
		t.Fatal(err)
	}
	r, err := db.Writer.Exec(`INSERT INTO downloads(group_id,message_id,file_name,file_path,file_size) VALUES('fixture',?,?,?,?)`, msg, filepath.Base(name), name, len(content))
	if err != nil {
		t.Fatal(err)
	}
	id, err := r.LastInsertId()
	if err != nil {
		t.Fatal(err)
	}
	return id
}
func waitBackup(t *testing.T, m *Manager, id int64, done, failed int64) {
	t.Helper()
	deadline := time.Now().Add(7 * time.Second)
	for time.Now().Before(deadline) {
		s, err := m.Status(context.Background(), id)
		if err == nil && s["completed24h"] == done && s["failed24h"] == failed && s["queued"] == int64(0) && s["processing"] == int64(0) && s["running"] == false {
			return
		}
		time.Sleep(10 * time.Millisecond)
	}
	s, e := m.Status(context.Background(), id)
	t.Fatalf("backup did not finish: %v %v", s, e)
}
func TestCredentialsMatchIndependentTGDCVectorAndRejectTampering(t *testing.T) {
	// Independently generated by Python cryptography AESGCM + hashlib.pbkdf2_hmac.
	blob, _ := hex.DecodeString("5447444301000102030405060708090a0bbc0c1a2f9971f233f07fb7ed7a700b234dbcee61632cbc2996846523de807048539534c5cda1385732a51409904b85a99b57d3a2e499bc79789cf4d519c73e759cf8")
	secret := bytes.Repeat([]byte{0x11}, 32)
	cfg, err := openConfig(blob, secret)
	if err != nil || cfg["password"] != "test-only" || cfg["rootPath"] != "/fixture/nas" {
		t.Fatalf("legacy vector: %v %v", cfg, err)
	}
	sealed, err := sealConfig(cfg, secret)
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Contains(sealed, []byte("test-only")) {
		t.Fatal("plaintext credential")
	}
	if _, err = openConfig(sealed, secret); err != nil {
		t.Fatal(err)
	}
	for _, i := range []int{0, 4, 5, 17, len(sealed) - 1} {
		bad := append([]byte(nil), sealed...)
		bad[i] ^= 1
		if _, err = openConfig(bad, secret); err == nil {
			t.Fatalf("tampered byte %d accepted", i)
		}
	}
	if _, err = openConfig(sealed, bytes.Repeat([]byte{0x22}, 32)); err == nil {
		t.Fatal("wrong secret accepted")
	}
}
func TestAutomaticMirrorIsDurableAndComparesContent(t *testing.T) {
	m, db, dir := fixtureManager(t, nil)
	target := filepath.Join(dir, "target")
	id := addLocal(t, m, target, "mirror")
	if err := m.Pause(context.Background(), id, true); err != nil {
		t.Fatal(err)
	}
	addSource(t, db, dir, "group/file.bin", "correct", 1)
	if err := os.MkdirAll(filepath.Join(target, "group"), 0700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(target, "group/file.bin"), []byte("WRONG!!"), 0600); err != nil {
		t.Fatal(err)
	}
	m.Close()
	opts := m.opts
	next, err := NewManager(context.Background(), opts)
	if err != nil {
		t.Fatal(err)
	}
	defer next.Close()
	s, err := next.Status(context.Background(), id)
	if err != nil || s["paused"] != true || s["queued"] != int64(1) {
		t.Fatalf("pause/queue not durable: %v %v", s, err)
	}
	if err = next.Pause(context.Background(), id, false); err != nil {
		t.Fatal(err)
	}
	waitBackup(t, next, id, 1, 0)
	raw, err := os.ReadFile(filepath.Join(target, "group/file.bin"))
	if err != nil || string(raw) != "correct" {
		t.Fatalf("same-size corrupt destination skipped: %q %v", raw, err)
	}
	for range 3 {
		if err = next.Run(context.Background(), id); err != nil {
			t.Fatal(err)
		}
	}
	jobs, err := next.Jobs(context.Background(), id, "", 50, 0, false)
	if err != nil || len(jobs) != 1 {
		t.Fatalf("duplicate queue jobs: %v %v", jobs, err)
	}
}
func TestMirrorTransactionRollbackAndMissingSource(t *testing.T) {
	m, db, dir := fixtureManager(t, nil)
	id := addLocal(t, m, filepath.Join(dir, "target"), "mirror")
	tx, err := db.Writer.Begin()
	if err != nil {
		t.Fatal(err)
	}
	if _, err = tx.Exec(`INSERT INTO downloads(group_id,message_id,file_path) VALUES('rollback',1,'missing')`); err != nil {
		t.Fatal(err)
	}
	if err = tx.Rollback(); err != nil {
		t.Fatal(err)
	}
	var count int
	if err = db.Reader.QueryRow(`SELECT count(*) FROM backup_jobs`).Scan(&count); err != nil || count != 0 {
		t.Fatalf("orphan job from rolled-back ingestion: %d %v", count, err)
	}
	if _, err = db.Writer.Exec(`INSERT INTO downloads(group_id,message_id,file_path) VALUES('missing',1,'missing')`); err != nil {
		t.Fatal(err)
	}
	m.Wake()
	waitBackup(t, m, id, 0, 1)
	jobs, _ := m.Jobs(context.Background(), id, "failed", 50, 0, false)
	if len(jobs) != 1 || !strings.Contains(jobs[0]["error"].(string), "local file missing") {
		t.Fatalf("missing file: %v", jobs)
	}
}
func TestLocalCancellationAndPathEscapeNeverPublish(t *testing.T) {
	root := t.TempDir()
	outside := t.TempDir()
	p, err := newLocal(map[string]any{"rootPath": root})
	if err != nil {
		t.Fatal(err)
	}
	defer p.Close()
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err = p.Upload(ctx, "file", strings.NewReader("x"), 1, nil); err == nil {
		t.Fatal("cancel ignored")
	}
	if _, err = os.Stat(filepath.Join(root, "file")); !errors.Is(err, os.ErrNotExist) {
		t.Fatal("cancel published")
	}
	if err = os.Symlink(outside, filepath.Join(root, "escape")); err != nil {
		t.Skip(err)
	}
	for _, name := range []string{"../outside", "/absolute", "escape/stolen", "a\\..\\b", "C:/outside"} {
		if _, err = p.Upload(context.Background(), name, strings.NewReader("secret"), 6, nil); err == nil {
			t.Fatalf("escape accepted %q", name)
		}
	}
	files, err := os.ReadDir(outside)
	if err != nil || len(files) != 0 {
		t.Fatal("wrote outside root")
	}
	if err = os.WriteFile(filepath.Join(root, ".tgdl-test-probe"), []byte("user file"), 0600); err != nil {
		t.Fatal(err)
	}
	if _, err = p.Test(context.Background()); err != nil {
		t.Fatal(err)
	}
	b, _ := os.ReadFile(filepath.Join(root, ".tgdl-test-probe"))
	if string(b) != "user file" {
		t.Fatal("probe clobbered existing file")
	}
}

type failureProvider struct {
	Provider
	calls   atomic.Int64
	started chan struct{}
	block   bool
}

func (p *failureProvider) Upload(ctx context.Context, name string, r io.ReadSeeker, size int64, progress func(int64)) (UploadResult, error) {
	n := p.calls.Add(1)
	if p.block {
		if n == 1 {
			close(p.started)
		}
		<-ctx.Done()
		return UploadResult{}, ctx.Err()
	}
	if n == 1 {
		return UploadResult{}, errors.New("transient upload error")
	}
	return p.Provider.Upload(ctx, name, r, size, progress)
}
func TestRetryTimerResumesWithoutUserAction(t *testing.T) {
	var fixture atomic.Pointer[failureProvider]
	m, db, dir := fixtureManager(t, func(ctx context.Context, name string, cfg map[string]any) (Provider, error) {
		p, e := nativeProvider(ctx, name, cfg)
		fp := &failureProvider{Provider: p}
		fixture.Store(fp)
		return fp, e
	})
	id := addLocal(t, m, filepath.Join(dir, "target"), "mirror")
	addSource(t, db, dir, "a.bin", "bytes", 1)
	m.Wake()
	waitBackup(t, m, id, 1, 0)
	jobs, _ := m.Jobs(context.Background(), id, "", 50, 0, false)
	if jobs[0]["attempts"] != int64(2) || fixture.Load().calls.Load() != 2 {
		t.Fatalf("retry did not run: %v", jobs)
	}
}
func TestShutdownJoinsUploadAndRestoresPendingJob(t *testing.T) {
	started := make(chan struct{})
	m, db, dir := fixtureManager(t, func(ctx context.Context, name string, cfg map[string]any) (Provider, error) {
		p, e := nativeProvider(ctx, name, cfg)
		return &failureProvider{Provider: p, started: started, block: true}, e
	})
	id := addLocal(t, m, filepath.Join(dir, "target"), "mirror")
	addSource(t, db, dir, "a.bin", "bytes", 1)
	m.Wake()
	select {
	case <-started:
	case <-time.After(3 * time.Second):
		t.Fatal("upload never started")
	}
	m.Close()
	var state string
	var attempts int
	if err := db.Reader.QueryRow(`SELECT status,attempts FROM backup_jobs LIMIT 1`).Scan(&state, &attempts); err != nil || state != "pending" || attempts != 0 {
		t.Fatalf("shutdown lost work: %s %d %v", state, attempts, err)
	}
	opts := m.opts
	opts.Factory = nil
	next, err := NewManager(context.Background(), opts)
	if err != nil {
		t.Fatal(err)
	}
	defer next.Close()
	waitBackup(t, next, id, 1, 0)
}
func TestSnapshotContainsRecoverableStateAndPrunesOnlySnapshots(t *testing.T) {
	m, _, dir := fixtureManager(t, nil)
	target := filepath.Join(dir, "target")
	id := addLocal(t, m, target, "snapshot")
	if _, err := m.Update(context.Background(), id, map[string]any{"retainCount": 1}); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(dir, "sessions"), 0700); err != nil {
		t.Fatal(err)
	}
	for name, content := range map[string]string{"secret.key": "test-session-key", "sessions/account.json": "test-encrypted-session", "config.json": "{}"} {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0600); err != nil {
			t.Fatal(err)
		}
	}
	if err := os.MkdirAll(filepath.Join(target, "snapshots"), 0700); err != nil {
		t.Fatal(err)
	}
	for _, name := range []string{"snapshot-20000101-000000.tar.gz", "user-data.tar.gz"} {
		if err := os.WriteFile(filepath.Join(target, "snapshots", name), []byte("keep unless owned snapshot"), 0600); err != nil {
			t.Fatal(err)
		}
	}
	if err := m.Run(context.Background(), id); err != nil {
		t.Fatal(err)
	}
	waitBackup(t, m, id, 1, 0)
	jobs, _ := m.Jobs(context.Background(), id, "", 50, 0, false)
	j := jobs[0]
	if _, err := os.Stat(j["snapshot_path"].(string)); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("staging not cleaned: %v", err)
	}
	f, err := os.Open(filepath.Join(target, j["remote_path"].(string)))
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	gz, err := gzip.NewReader(f)
	if err != nil {
		t.Fatal(err)
	}
	defer gz.Close()
	tr := tar.NewReader(gz)
	files := map[string][]byte{}
	for {
		h, e := tr.Next()
		if errors.Is(e, io.EOF) {
			break
		}
		if e != nil {
			t.Fatal(e)
		}
		files[h.Name], e = io.ReadAll(tr)
		if e != nil {
			t.Fatal(e)
		}
	}
	if !bytes.HasPrefix(files["db.sqlite"], []byte("SQLite format 3")) || string(files["secret.key"]) != "test-session-key" || string(files["sessions/account.json"]) != "test-encrypted-session" {
		t.Fatalf("incomplete restore state: %v", files)
	}
	restorePath := filepath.Join(t.TempDir(), "db.sqlite")
	if err = os.WriteFile(restorePath, files["db.sqlite"], 0600); err != nil {
		t.Fatal(err)
	}
	restored, err := sql.Open("sqlite", restorePath)
	if err != nil {
		t.Fatal(err)
	}
	defer restored.Close()
	var integrity string
	if err = restored.QueryRow("PRAGMA integrity_check").Scan(&integrity); err != nil || integrity != "ok" {
		t.Fatalf("invalid restored DB: %q %v", integrity, err)
	}
	if _, err = os.Stat(filepath.Join(target, "snapshots/snapshot-20000101-000000.tar.gz")); !errors.Is(err, os.ErrNotExist) {
		t.Fatal("old snapshot retained")
	}
	if _, err = os.Stat(filepath.Join(target, "snapshots/user-data.tar.gz")); err != nil {
		t.Fatal("unrelated object deleted")
	}
}
func TestEncryptedAndUnimplementedTransfersRemainPending(t *testing.T) {
	m, db, dir := fixtureManager(t, nil)
	id := addLocal(t, m, filepath.Join(dir, "target"), "mirror")
	if _, err := m.Encryption(context.Background(), id, true, "test-pass", false); err != nil {
		t.Fatal(err)
	}
	if _, err := m.Encryption(context.Background(), id, true, "wrong-pass", true); err == nil {
		t.Fatal("wrong key accepted")
	}
	addSource(t, db, dir, "a.bin", "must not leak", 1)
	m.Wake()
	deadline := time.Now().Add(2 * time.Second)
	for {
		status, e := m.Status(context.Background(), id)
		if e != nil {
			t.Fatal(e)
		}
		if status["lastError"] != nil {
			break
		}
		if time.Now().After(deadline) {
			t.Fatal("missing blocked-state error")
		}
		time.Sleep(10 * time.Millisecond)
	}
	jobs, _ := m.Jobs(context.Background(), id, "", 50, 0, false)
	if jobs[0]["attempts"] != int64(0) || jobs[0]["status"] != "pending" {
		t.Fatalf("blocked encryption burned attempts: %v", jobs)
	}
	if _, err := os.Stat(filepath.Join(dir, "target/a.bin")); !errors.Is(err, os.ErrNotExist) {
		t.Fatal("encrypted job leaked plaintext")
	}
}
func TestScheduleSurvivesRestartAndRejectsMalformedCron(t *testing.T) {
	m, db, dir := fixtureManager(t, nil)
	id := addLocal(t, m, filepath.Join(dir, "target"), "snapshot")
	now := time.Now()
	m.scheduleAt(now)
	m.scheduleAt(now)
	m.Close()
	var n int
	if err := db.Reader.QueryRow(`SELECT count(*) FROM backup_jobs WHERE destination_id=?`, id).Scan(&n); err != nil || n != 1 {
		t.Fatalf("duplicate scheduled job: %d %v", n, err)
	}
	next, err := NewManager(context.Background(), m.opts)
	if err != nil {
		t.Fatal(err)
	}
	defer next.Close()
	next.scheduleAt(now)
	if err = db.Reader.QueryRow(`SELECT count(*) FROM backup_jobs WHERE destination_id=?`, id).Scan(&n); err != nil || n != 1 {
		t.Fatalf("restart repeated cron minute: %d %v", n, err)
	}
	for _, expr := range []string{"* * *", "60 * * * *", "*/0 * * * *", "x * * * *", "* * 0 * *"} {
		if validateCron(expr) == nil {
			t.Fatalf("invalid cron accepted: %s", expr)
		}
	}
}

// An edit may arrive after a worker claimed the old message's backup. The
// completed old transfer must not erase the new request in that same job row.
type editDuringUpload struct {
	Provider
	edit  func()
	calls int
}

func (p *editDuringUpload) Upload(ctx context.Context, name string, src io.ReadSeeker, size int64, progress func(int64)) (UploadResult, error) {
	p.calls++
	result, err := p.Provider.Upload(ctx, name, src, size, progress)
	if p.calls == 1 {
		p.edit()
	}
	return result, err
}
func TestEditedMediaDuringUploadKeepsNewRevisionPending(t *testing.T) {
	var edit func()
	m, db, dir := fixtureManager(t, func(ctx context.Context, name string, cfg map[string]any) (Provider, error) {
		p, e := nativeProvider(ctx, name, cfg)
		return &editDuringUpload{Provider: p, edit: func() { edit() }}, e
	})
	target := filepath.Join(dir, "target")
	id := addLocal(t, m, target, "mirror")
	if err := m.Pause(context.Background(), id, true); err != nil {
		t.Fatal(err)
	}
	row := addSource(t, db, dir, "old.bin", "old contents", 1)
	if err := os.WriteFile(filepath.Join(dir, "downloads/new.bin"), []byte("new contents"), 0600); err != nil {
		t.Fatal(err)
	}
	edits := make(chan error, 1)
	edit = func() {
		_, err := db.Writer.Exec(`UPDATE downloads SET file_path='new.bin',file_hash='new-hash' WHERE id=?`, row)
		edits <- err
	}
	if err := m.Pause(context.Background(), id, false); err != nil {
		t.Fatal(err)
	}
	waitBackup(t, m, id, 1, 0)
	if err := <-edits; err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(filepath.Join(target, "new.bin"))
	if err != nil || string(b) != "new contents" {
		t.Fatalf("edited media lost: %q %v", b, err)
	}
	jobs, _ := m.Jobs(context.Background(), id, "", 50, 0, false)
	if len(jobs) != 1 || jobs[0]["remote_path"] != "new.bin" {
		t.Fatalf("revision replaced job unexpectedly: %v", jobs)
	}
}
func TestBackupSecretRedactionAndPassphraseVerificationAcrossRestart(t *testing.T) {
	m, _, dir := fixtureManager(t, nil)
	ctx := context.Background()
	d, err := m.Create(ctx, map[string]any{"name": "credentials", "provider": "s3", "enabled": false, "config": map[string]any{"bucket": "test", "region": "test-region", "secretAccessKey": "test-only-secret", "accessKeyId": "test-only-id"}})
	if err != nil {
		t.Fatal(err)
	}
	id := d["id"].(int64)
	if _, err = m.Update(ctx, id, map[string]any{"config": map[string]any{"bucket": "changed", "secretAccessKey": ""}}); err != nil {
		t.Fatal(err)
	}
	public, err := m.Config(ctx, id)
	if err != nil || public["secretAccessKey"] != nil || public["accessKeyId"] != nil || public["bucket"] != "changed" {
		t.Fatalf("secret projection: %v %v", public, err)
	}
	row, err := m.load(ctx, id)
	if err != nil {
		t.Fatal(err)
	}
	private, err := m.config(ctx, row)
	if err != nil || private["secretAccessKey"] != "test-only-secret" {
		t.Fatal("empty edit replaced credential")
	}
	local := addLocal(t, m, filepath.Join(dir, "target"), "mirror")
	if _, err = m.Encryption(ctx, local, true, "correct", false); err != nil {
		t.Fatal(err)
	}
	m.Close()
	next, err := NewManager(ctx, m.opts)
	if err != nil {
		t.Fatal(err)
	}
	defer next.Close()
	s, err := next.Status(ctx, local)
	if err != nil || s["encryptionUnlocked"] != false {
		t.Fatalf("key persisted on disk: %v %v", s, err)
	}
	if _, err = next.Encryption(ctx, local, true, "wrong", true); err == nil {
		t.Fatal("wrong key after restart accepted")
	}
	if _, err = next.Encryption(ctx, local, true, "correct", true); err != nil {
		t.Fatal(err)
	}
}
func BenchmarkLocalMirrorVerify1MiB(b *testing.B) {
	p, err := newLocal(map[string]any{"rootPath": b.TempDir()})
	if err != nil {
		b.Fatal(err)
	}
	defer p.Close()
	data := bytes.Repeat([]byte{7}, 1<<20)
	if _, err = p.Upload(context.Background(), "file", bytes.NewReader(data), int64(len(data)), nil); err != nil {
		b.Fatal(err)
	}
	b.SetBytes(int64(len(data)))
	b.ReportAllocs()
	b.ResetTimer()
	for range b.N {
		result, err := p.Upload(context.Background(), "file", bytes.NewReader(data), int64(len(data)), nil)
		if err != nil || !result.Skipped {
			b.Fatalf("verification failed: %v %v", result, err)
		}
	}
}

func TestSnapshotRetentionOutboxResumesAfterRestart(t *testing.T) {
	m, db, dir := fixtureManager(t, nil)
	ctx := context.Background()
	target := filepath.Join(dir, "target")
	id := addLocal(t, m, target, "snapshot")
	if _, err := m.Update(ctx, id, map[string]any{"retainCount": 1}); err != nil {
		t.Fatal(err)
	}
	if err := m.Pause(ctx, id, true); err != nil {
		t.Fatal(err)
	}
	stage := filepath.Join(dir, "backups/snapshot-20261009-010000.tar.gz")
	for name, content := range map[string]string{stage: "uploaded", filepath.Join(target, "snapshots/snapshot-20261009-010000.tar.gz"): "uploaded", filepath.Join(target, "snapshots/snapshot-20261008-010000.tar.gz"): "old"} {
		if err := os.MkdirAll(filepath.Dir(name), 0700); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(name, []byte(content), 0600); err != nil {
			t.Fatal(err)
		}
	}
	result, err := db.Writer.Exec(`INSERT INTO backup_jobs(destination_id,snapshot_path,remote_path,status,finished_at,bytes_uploaded) VALUES(?,?,?,'done',?,8)`, id, stage, "snapshots/snapshot-20261009-010000.tar.gz", time.Now().UnixMilli())
	if err != nil {
		t.Fatal(err)
	}
	jobID, _ := result.LastInsertId()
	if _, err = db.Writer.Exec(`INSERT INTO native_backup_retention(job_id) VALUES(?)`, jobID); err != nil {
		t.Fatal(err)
	}
	m.Close()
	next, err := NewManager(ctx, m.opts)
	if err != nil {
		t.Fatal(err)
	}
	defer next.Close()
	if err = next.Pause(ctx, id, false); err != nil {
		t.Fatal(err)
	}
	deadline := time.Now().Add(3 * time.Second)
	for {
		var n int
		if err = db.Reader.QueryRow(`SELECT count(*) FROM native_backup_retention`).Scan(&n); err != nil {
			t.Fatal(err)
		}
		if n == 0 {
			break
		}
		if time.Now().After(deadline) {
			t.Fatal("cleanup never resumed")
		}
		time.Sleep(10 * time.Millisecond)
	}
	for _, name := range []string{stage, filepath.Join(target, "snapshots/snapshot-20261008-010000.tar.gz")} {
		if _, err = os.Stat(name); !errors.Is(err, os.ErrNotExist) {
			t.Fatalf("stale snapshot remains: %v", err)
		}
	}
	raw, err := os.ReadFile(filepath.Join(target, "snapshots/snapshot-20261009-010000.tar.gz"))
	if err != nil || string(raw) != "uploaded" {
		t.Fatalf("retained snapshot lost: %v", err)
	}
}
