FROM nvidia/cuda:12.4.1-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY main.py .

ENV TGDL_NSFW_HOST=0.0.0.0
ENV TGDL_NSFW_PORT=8012

EXPOSE 8012

CMD ["python3", "main.py"]
